version: "3.8"
services:
    whatsapp-notification-api-service:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1234:4000"
        volumes:
            # setup file or folder public
            - whatsapp-notification-api-service:/app/.wwebjs_auth
            - eng.traineddata:/app/eng.traineddata
            - osd.traineddata:/app/osd.traineddata
        network_mode: bridge
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    whatsapp-notification-api-service:
        external: false
    eng.traineddata:
        external: false
    osd.traineddata:
        external: false
