version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.11
    restart: always
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672' # Port RabbitMQ
      - '25672:25672'
      - '15672:15672' # Port Dashboard RabbitMQ
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
      - RABBITMQ_DEFAULT_USER=jefripunza
      - RABBITMQ_DEFAULT_PASS=r00t_d3v3L0pm3nt
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Volume untuk data RabbitMQ
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  rabbitmq_data:
    driver: local